# Generated by Django 4.1 on 2022-08-17 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 16, 36, 59, 25209, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
