# Generated by Django 4.1 on 2022-08-17 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_post_time_pub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('content', models.CharField(max_length=1000)),
                ('time_pub', models.DateTimeField(default=datetime.datetime(2022, 8, 17, 18, 34, 42, 465547, tzinfo=datetime.timezone.utc), verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 18, 34, 42, 465192, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
